### ISSUE TITLE
画像処理を高速省メモリのlibvips + image_processing + Active Storageに移行したい

### ISSUE THREAD

**Issue by west2538** [west2538/machiroute_oss#7]
* CentOS 7でlibvips v8.8.1のインストールを試みたが、依存関係のあるパッケージglib-2.6が最新リポジトリになく断念

* 参考記事
https://gorails.com/forum/rails-6-0-heroku-active-storage-vips

* 基本的なインストール方法
https://github.com/libvips/libvips

**Comment by west2538** [comment]
CentOS 7にlibvips v8.8.1をインストールするときは `yum -y install glib2-devel` が必要だった

**Comment by west2538** [comment]
あと `yum install libjpeg-turbo-devel` も実行した

**Comment by west2538** [comment]
エラーが出る...

```
Vips::Error (VipsForeignLoad: "/tmp/ActiveStorage-13-20190831-13270-1brk544.jpg" is not a known file format
VipsForeignLoad: "/tmp/ActiveStorage-13-20190831-13270-1brk544.jpg" is not a known file format
):
```

**Comment by west2538** [comment]
Remiのリポジトリから最新のlibvips 8.8.2をインストールしてみた

`yum --enablerepo=remi install vips`

エラーが出る...

```
LoadError (Could not open library 'vips': vips: cannot open shared object file: No such file or directory.
Could not open library 'libvips.so': libvips.so: cannot open shared object file: No such file or directory):
```

**Comment by west2538** [comment]
libvips v8.8.2をmake installしてみた

```
# wget https://github.com/libvips/libvips/releases/download/v8.8.2/vips-8.8.2.tar.gz
# tar zxf vips-8.8.2.tar.gz
# cd vips-8.8.2
# make
# make install
```

違うエラーが出た...

```
TypeError (no implicit conversion to float from string):
  
ruby-vips (2.0.14) lib/vips/gvalue.rb:103:in `g_value_set_double'
ruby-vips (2.0.14) lib/vips/gvalue.rb:103:in `set'
ruby-vips (2.0.14) lib/vips/object.rb:169:in `set'
ruby-vips (2.0.14) lib/vips/operation.rb:154:in `set'
ruby-vips (2.0.14) lib/vips/operation.rb:314:in `block in call'
ruby-vips (2.0.14) lib/vips/operation.rb:309:in `each_index'
ruby-vips (2.0.14) lib/vips/operation.rb:309:in `call'
ruby-vips (2.0.14) lib/vips/image.rb:211:in `method_missing'
```

**Comment by west2538** [comment]
試しに `make check` してみた

```
# cd vips-8.8.2
# make check
```

ひとつエラーが見つかった

```
building huge test PNG image ... VipsForeignSave: "/root/vips-8.8.2/test/tmp-4238/huge.png" is not a known file format
ok
testing vipsthumbnail ... /root/vips-8.8.2/tools/.libs/lt-vipsthumbnail: unable to thumbnail /root/vips-8.8.2/test/tmp-4238/huge.png
VipsForeignLoad: file "/root/vips-8.8.2/test/tmp-4238/huge.png" not found
vipsthumbnail failed in basic mode
FAIL test_seq.sh (exit status: 1)
```

なので `yum install libpng-devel' を実行して再度 'make check' してみたら同じようなエラー

```
building huge test PNG image ... VipsForeignSave: "/root/vips-8.8.2/test/tmp-10592/huge.png" is not a known file format
ok
testing vipsthumbnail ... /root/vips-8.8.2/tools/.libs/lt-vipsthumbnail: unable to thumbnail /root/vips-8.8.2/test/tmp-10592/huge.png
VipsForeignLoad: file "/root/vips-8.8.2/test/tmp-10592/huge.png" not found
vipsthumbnail failed in basic mode
FAIL test_seq.sh (exit status: 1)
```

**Comment by west2538** [comment]
```
# yum install libexif-devel
# yum install libtiff-devel
# make check
```
上記でも同様のエラー発生

そこで最新のImageMagick7をインストール
```
# yum install -y https://www.imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-libs-7.0.8-62.x86_64.rpm
# yum install -y https://www.imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-7.0.8-62.x86_64.rpm
# yum install -y https://www.imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-devel-7.0.8-62.x86_64.rpm
```
以上をしても `make check` で同じエラーが発生

さらに ` yum groupinstall "Development Tools" `を実行して開発ライブラリを一気にインストール

解決せず...

**Comment by west2538** [comment]
`./configure` で `no` となっているライブラリを片っ端からインストール。そのあと
```
# make
# make install
# make check
```
をしたらエラーメッセージが出なくなった!!

**Comment by west2538** [comment]
image_processing + ruby-vipsの構成になったためvariantのコードを下記のように変更しました

`image_tag post.image.variant(resize_to_fit: [288,288], autorot: true, saver: { strip: true, quality: 60 }), :class => "card-img-top"`

**Comment by west2538** [comment]
Herokuでも動作確認完了！
